volumes:
  classroom_data:

services:
  db:
    container_name: classroom-database
    image: postgres:17-alpine
    restart: on-failure
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=classroom
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - classroom_data:/var/lib/postgresql/data

  bot-discord:
    container_name: classroom-bot-discord
    build:
      context: ./apps/bot
      dockerfile: Dockerfile
    restart: on-failure
    # environment:
    #   - DATABASE_URL=postgresql://local:local@db:5432/classroom
    #   - DISCORD_TOKEN=${DISCORD_TOKEN}
    #   - TYPHOON_KEY=${TYPHOON_KEY}
    depends_on:
      - db
    env_file:
      - ./apps/bot/.env

  bot-assignment:
    container_name: classroom-bot-assignment
    build:
      context: ./apps/assignment-bot
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./apps/assignment-bot/.env
